// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gefsvwcyxxgyfaandyjp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZnN2d2N5eHhneWZhYW5keWpwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMjYwNzUsImV4cCI6MjA1NzgwMjA3NX0.bqoDZOLq86zQ9GjaEomYAhBGkBiiGiZj-Kn_qD9xX5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);